Drop DATABASE wot; -- Suppression de la table existante

CREATE DATABASE wot CHARACTER SET 'utf8';  -- Creation de la base

USE wot; -- Sélection de la base wot

CREATE TABLE Nation -- Création de la table contenant les nations
(id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
nation VARCHAR(15) NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB;

CREATE TABLE Canon -- Création de la table contenant les différents canons
(id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
nom	 VARCHAR(50) NOT NULL,
calibre	SMALLINT UNSIGNED NOT NULL,
nombre_obus	TINYINT UNSIGNED NOT NULL,
cadence_tir	DECIMAL(5,2) UNSIGNED NOT NULL,
temps_chargement_total DECIMAL(5,2) UNSIGNED NOT NULL,
penetration1 SMALLINT UNSIGNED NOT NULL,
penetration2 SMALLINT UNSIGNED,
penetration3 SMALLINT UNSIGNED,
degat_moyen1 SMALLINT UNSIGNED NOT NULL,
degat_moyen2 SMALLINT UNSIGNED,
degat_moyen3 SMALLINT UNSIGNED,
dispersion DECIMAL(4,2) UNSIGNED NOT NULL,
vitesse_visee DECIMAL(4,2) UNSIGNED NOT NULL,
poids SMALLINT UNSIGNED NOT NULL,
tier TINYINT UNSIGNED NOT NULL,
nation VARCHAR(15) NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB;

CREATE TABLE Moteur
(id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
nom	 VARCHAR(50) NOT NULL,
puissance_moteur SMALLINT UNSIGNED NOT NULL,
probabilite_incendie TINYINT UNSIGNED NOT NULL,
poids SMALLINT UNSIGNED NOT NULL,
tier TINYINT UNSIGNED NOT NULL,
nation VARCHAR(15) NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB;

CREATE TABLE Radio
(id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
nom	 VARCHAR(50) NOT NULL,
portee_radio SMALLINT UNSIGNED NOT NULL,
poids SMALLINT UNSIGNED NOT NULL,
tier TINYINT UNSIGNED NOT NULL,
nation VARCHAR(15) NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB;

CREATE TABLE Suspension
(id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
nom	 VARCHAR(50) NOT NULL,
charge_max SMALLINT UNSIGNED NOT NULL,
vitesse_rotation TINYINT UNSIGNED NOT NULL,
poids SMALLINT UNSIGNED NOT NULL,
tier TINYINT UNSIGNED NOT NULL,
nation VARCHAR(15) NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB;

CREATE TABLE Tourelle
(id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
nom	 VARCHAR(50) NOT NULL,
poids SMALLINT UNSIGNED NOT NULL,
tier TINYINT UNSIGNED NOT NULL,
nation VARCHAR(15) NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;

CREATE TABLE Tank
(id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
nation VARCHAR(15) NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB;

SOURCE C://wot//ChargementNation.sql;

SELECT * FROM Nation;

SELECT * FROM Canon;

SELECT * FROM Moteur;

SELECT * FROM Radio;

SELECT * FROM Suspension;